DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255) NOT NULL UNIQUE,
  answers TEXT
);

DROP TABLE IF EXISTS otps;

CREATE TABLE otps (
  id SERIAL PRIMARY KEY,
  userid INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  otp VARCHAR(6) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);